---
- name: Ubuntu Paket Güncelleme
  hosts: all
  become: yes
  vars:
    update_apparmor: yes
    update_apt: yes
    update_cloud_init: no
    update_coreutils: no

  tasks:
    - name: apparmor güncelle
      apt:
        name: apparmor
        state: latest
      when: update_apparmor | bool

    - name: apt güncelle
      apt:
        name: apt
        state: latest
      when: update_apt | bool
